# Generated by Django 3.2.4 on 2023-09-13 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='mproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('ppic', models.ImageField(null=True, upload_to='static/myproduct')),
                ('total_discount', models.IntegerField(null=True)),
                ('discount_price', models.IntegerField(null=True)),
                ('pdate', models.DateField(null=True)),
                ('pcategoty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
                ('psubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subcategory')),
            ],
        ),
    ]
