# Generated by Django 3.2.4 on 2023-09-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_mproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mproduct',
            old_name='pcategoty',
            new_name='pcategory',
        ),
    ]
