# Generated by Django 3.2.4 on 2023-09-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_pcategoty_mproduct_pcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproduct',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
