# Generated by Django 3.2.4 on 2023-09-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_mproduct_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mproduct',
            name='product_quantity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
