# Generated by Django 3.2.4 on 2023-09-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_mproduct_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200, null=True)),
                ('semail', models.CharField(max_length=200, null=True)),
                ('smobile', models.IntegerField(max_length=30, null=True)),
                ('spassword', models.CharField(max_length=200, null=True)),
                ('sprofile', models.ImageField(null=True, upload_to='static/register')),
                ('saddress', models.TextField()),
            ],
        ),
    ]
