# Generated by Django 3.2.4 on 2023-09-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='smobile',
            field=models.IntegerField(null=True),
        ),
    ]
