# Generated by Django 3.2.4 on 2023-09-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_register_smobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='sprofile',
            new_name='profile',
        ),
    ]
