# Generated by Django 3.2.4 on 2023-09-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactus',
        ),
    ]
