# Generated by Django 3.2.4 on 2023-09-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_contact_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('fpic', models.ImageField(null=True, upload_to='static/faculty')),
                ('finformation', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
