# Generated by Django 3.2.4 on 2023-09-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20230915_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='of_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of_pic', models.ImageField(null=True, upload_to='static/offer_pic')),
                ('of_date', models.DateField(null=True)),
            ],
        ),
    ]
