# Generated by Django 3.2.4 on 2023-09-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_of_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AlterField(
            model_name='register',
            name='semail',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
