# Generated by Django 3.2.4 on 2023-09-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
