# Generated by Django 3.2.4 on 2023-09-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_myorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myorder',
            new_name='myorders',
        ),
    ]
