# Generated by Django 3.2.4 on 2023-09-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_rename_myorder_myorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myorders',
            new_name='myorder',
        ),
    ]
